In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

In [33]:
df = pd.read_csv("./Data/head_brain.csv")
df.head(220)

     Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
..      ...        ...              ...                  ...
215       2          2             3156                 1225
216       2          2             3246                 1180
217       2          2             3170                 1178
218       2          2             3268                 1142
219       2          2             3389                 1130

[220 rows x 4 columns]

In [34]:
# Create classification label
df['Brain_Class'] = (df['Brain Weight(grams)'] > df['Brain Weight(grams)'].mean()).astype(int)
df.head()

   Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)  Brain_Class
0       1          1             4512                 1530            1
1       1          1             3738                 1297            1
2       1          1             4261                 1335            1
3       1          1             3777                 1282            0
4       1          1             4177                 1590            1

In [10]:
X = df[['Gender', 'Age Range', 'Head Size(cm^3)']]
y = df['Brain_Class']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [35]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [13]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7916666666666666

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.96      0.81        23
           1       0.94      0.64      0.76        25

    accuracy                           0.79        48
   macro avg       0.83      0.80      0.79        48
weighted avg       0.83      0.79      0.79        48

In [14]:
sample = [[1,1,4200]]  # Gender, Age Range, Head Size

prediction = model.predict(sample)

if prediction[0] == 1:
    print("Brain Weight: High")
else:
    print("Brain Weight: Low")

Brain Weight: High

C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(